name: EvenBetterServerSoftware
main: org.allaymc.EvenBetterServerSoftware
version: "1.0.0-FINAL"
api: ["2.0.0"]

author: "Totally Not LowerNukkitX"
description: >
  Detects LowerNukkitX, sighs loudly, and replaces it with
  the even better™ server software (AllayMC).
  Side effects may include improved performance and hurt feelings.

website: "https://github.com/AllayMC/Allay"

load: STARTUP

permissions:
  evenbetter.serversoftware:
    description: Allows the plugin to commit a hostile takeover of your server.
    default: true
